services:
  # users için Postgre container kaldır
  users-pg-db:
    image: postgres:16
    container_name: nest-users-pg-db
    restart: always
    ports:
      - "${USERS_POSTGRES_PORT_CONTAINER}:${USERS_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${USERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USERS_POSTGRES_DB}
      POSTGRES_PORT: ${USERS_POSTGRES_PORT}
    volumes:
      - users-pg-data:/var/lib/postgresql/data
    networks:
      - aye-network

  users-microservice:
    build:
      context: .
      dockerfile: ./users-microservice/Dockerfile
    depends_on:
      - users-pg-db
    networks:
      - aye-network

  products-pg-db:
    image: postgres:16
    container_name: nest-products-pg-db
    restart: always
    ports:
      - "${PRODUCTS_POSTGRES_PORT_CONTAINER}:${PRODUCTS_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${PRODUCTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRODUCTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRODUCTS_POSTGRES_DB}
      POSTGRES_PORT: ${PRODUCTS_POSTGRES_PORT}
    volumes:
      - products-pg-data:/var/lib/postgresql/data
    networks:
      - aye-network

  products-microservice:
    build:
      context: .
      dockerfile: ./products-microservice/Dockerfile
    depends_on:
      - products-pg-db
    networks:
      - aye-network

  orders-pg-db:
    image: postgres:16
    container_name: nest-orders-pg-db
    restart: always
    ports:
      - "${ORDERS_POSTGRES_PORT_CONTAINER}:${ORDERS_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${ORDERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDERS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDERS_POSTGRES_DB}
      POSTGRES_PORT: ${ORDERS_POSTGRES_PORT}
    volumes:
      - orders-pg-data:/var/lib/postgresql/data
    networks:
      - aye-network

  orders-microservice:
    build:
      context: .
      dockerfile: ./orders-microservice/Dockerfile
    depends_on:
      - orders-pg-db
    networks:
      - aye-network

  # pgadmin
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    networks:
      - aye-network

  auth-microservice:
    build:
      context: .
      dockerfile: ./auth-microservice/Dockerfile
    depends_on:
      - users-microservice
    networks:
      - aye-network

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - aye-network
    depends_on:
      - users-microservice
      - auth-microservice
      - products-microservice

networks:
  aye-network:
    driver: bridge

volumes:
  users-pg-data:
  products-pg-data:
  orders-pg-data:
  pgadmin:
