services:
  libs:
    build:
      context: .
      dockerfile: ./libs/dockerfile
    volumes:
      - libs-dist:/usr/src/app/libs/dist
      - libs-modules:/usr/src/app/libs/node_modules

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - aye-network
    volumes:
      - mongo-data:/data/db

  # users için Postgre container kaldır
  users-pg-db:
    image: postgres:16
    container_name: nest-users-pg-db
    restart: always
    ports:
      - "${USERS_POSTGRES_PORT_CONTAINER}:${USERS_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${USERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USERS_POSTGRES_DB}
      POSTGRES_PORT: ${USERS_POSTGRES_PORT}
    volumes:
      - users-pg-data:/var/lib/postgresql/data
    networks:
      - aye-network

  users-microservice:
    build:
      context: .
      dockerfile: ./users-microservice/Dockerfile
    env_file:
      - .env
    depends_on:
      - libs
      - users-pg-db
    volumes:
      - ./users-microservice:/usr/src/app/users-microservice
      - /usr/src/app/users-microservice/node_modules
      - libs-dist:/usr/src/app/libs/dist
      - libs-modules:/usr/src/app/libs/node_modules
    networks:
      - aye-network

  products-pg-db:
    image: postgres:16
    container_name: nest-products-pg-db
    restart: always
    ports:
      - "${PRODUCTS_POSTGRES_PORT_CONTAINER}:${PRODUCTS_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${PRODUCTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRODUCTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRODUCTS_POSTGRES_DB}
      POSTGRES_PORT: ${PRODUCTS_POSTGRES_PORT}
    volumes:
      - products-pg-data:/var/lib/postgresql/data
    networks:
      - aye-network

  products-microservice:
    build:
      context: .
      dockerfile: ./products-microservice/Dockerfile
    env_file:
      - .env
    depends_on:
      libs:
        condition: service_started
      products-pg-db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./products-microservice:/usr/src/app/products-microservice
      - /usr/src/app/products-microservice/node_modules
      - libs-dist:/usr/src/app/libs/dist
      - libs-modules:/usr/src/app/libs/node_modules
    networks:
      - aye-network

  orders-pg-db:
    image: postgres:16
    container_name: nest-orders-pg-db
    restart: always
    ports:
      - "${ORDERS_POSTGRES_PORT_CONTAINER}:${ORDERS_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${ORDERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDERS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDERS_POSTGRES_DB}
      POSTGRES_PORT: ${ORDERS_POSTGRES_PORT}
    volumes:
      - orders-pg-data:/var/lib/postgresql/data
    networks:
      - aye-network

  orders-microservice:
    build:
      context: .
      dockerfile: ./orders-microservice/Dockerfile
    env_file:
      - .env
    depends_on:
      - libs
      - orders-pg-db
    volumes:
      - ./orders-microservice:/usr/src/app/orders-microservice
      - /usr/src/app/orders-microservice/node_modules
      - libs-dist:/usr/src/app/libs/dist
      - libs-modules:/usr/src/app/libs/node_modules
    networks:
      - aye-network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - aye-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - aye-network

  notifications-microservice:
    build:
      context: .
      dockerfile: ./notifications-microservice/Dockerfile
    depends_on:
      - libs
      - kafka
    volumes:
      - ./notifications-microservice:/usr/src/app/notifications-microservice
      - /usr/src/app/notifications-microservice/node_modules
      - libs-dist:/usr/src/app/libs/dist
      - libs-modules:/usr/src/app/libs/node_modules
    networks:
      - aye-network

  auth-microservice:
    build:
      context: .
      dockerfile: ./auth-microservice/Dockerfile
    env_file:
      - .env
    depends_on:
      - libs
      - users-microservice
    volumes:
      - ./auth-microservice:/usr/src/app/auth-microservice
      - /usr/src/app/auth-microservice/node_modules
      - libs-dist:/usr/src/app/libs/dist
      - libs-modules:/usr/src/app/libs/node_modules
    networks:
      - aye-network

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - aye-network
    depends_on:
      - libs
      - users-microservice
      - auth-microservice
      - products-microservice
      - orders-microservice
    volumes:
      - ./api-gateway:/usr/src/app/api-gateway
      - /usr/src/app/api-gateway/node_modules
      - libs-dist:/usr/src/app/libs/dist
      - libs-modules:/usr/src/app/libs/node_modules

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - aye-network

  # pgadmin
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    networks:
      - aye-network

networks:
  aye-network:
    driver: bridge

volumes:
  users-pg-data:
  products-pg-data:
  orders-pg-data:
  mongo-data:
  pgadmin:
  libs-dist:
  libs-modules:
